# Generated by Django 5.1.2 on 2024-10-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('region', models.IntegerField(choices=[(1, 'Manzini'), (2, 'Hhohho'), (3, 'Shiselweni'), (4, 'Lubombo')], default=1)),
                ('licence_number', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=100)),
                ('valid_up_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_scan', models.ImageField(null=True, upload_to='scans/')),
                ('is_keypad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.driver')),
            ],
        ),
    ]
