# Generated by Django 5.1.2 on 2025-05-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_drivertickets_driverticket_rename_scans_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id',
            field=models.CharField(default='lindelw', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverTicket',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
